name: deploy
on: 
  push:
    branches:
      - master
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - name: 'set git identity'
              run: 'git config user.email "michael.vytlingam@gmail.com"'
              run: 'git config user.name "Michael Vytlingam"'
            - name: 'npm install'
              run: 'npm install'
            - name: 'npm run predeploy'
              run: 'npm run predeploy'
            - name: 'npm run deploy'
              run: 'npm run deploy'